### ISSUE TITLE
Authentication using cookies

### ISSUE THREAD

**Issue by jim0020** [apache/cordova-plugin-file-transfer#202]
If I'm connecting to my server using AJAX calls with the option

`xhrFields: { withCredentials: true },`

how can I do this in calls to FileTransfer?  It appears that FileTransfer only supports basic authentication.

**Comment by timbru31** [comment]
Basically the "withCredentials" sends the corresponding cookie values as an HTTP header. One can mimic this behavior and supply the cookie(s) in the request headers field.
More information on the Cookie Header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie
