### ISSUE TITLE
MacOS Support?

### ISSUE THREAD

**Issue by theparmis** [apache/cordova-plugin-file-transfer#205]
Hello everybody,
Any macOS support?
Is there any alternative for this plugin that's work on MacOS?

Thanks!

**Comment by theparmis** [comment]
Yes Cordova OSX. Any support  for file-transfer on "cordova platform osx"?
Thanks!

**Comment by janpio** [comment]
No, there is no implementation for `osx`: https://github.com/apache/cordova-plugin-file-transfer/tree/master/src

**Comment by theparmis** [comment]
What about alternatives?
Thank!

**Comment by janpio** [comment]
Sorry, no idea. One could certainly implement support for `osx` and add it to this plugin with a PR - we would be very happy to accept that.
