### ISSUE TITLE
After upload successfully to s3 bucket returns empty response

### ISSUE THREAD

**Issue by rameshSolutionFuse** [apache/cordova-plugin-file-transfer#207]
i'm using this plugin in ionic 3 and trying to upload images to s3 bucket, its uploading image but its not returning anything like url etc...

ionic v3
 "cordova-plugin-file-transfer": "^1.7.1",

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
