### ISSUE TITLE
When ionic3 uploads files with the file-transfer plug-in, neither successful nor failed callbacks are executed?

### ISSUE THREAD

**Issue by 365436741** [apache/cordova-plugin-file-transfer#220]
When ionic3 uploads files with the file-transfer plug-in, neither successful nor failed callbacks are executed?
const fileTransfer: FileTransferObject = this.transfer.create();

fileTransfer.upload(that.imgPath, encodeURI(url), options).then(function (data) {

console.log('ok');

}, function (err) {

console.log('err');

});

android5.0    cordova-plugin-file-transfer1.7.1

**Comment by 365436741** [comment]
android

**Comment by 365436741** [comment]
1.7.1

**Comment by timbru31** [comment]
Closing due to lack of feedback.
