### ISSUE TITLE
IOS 12 file download says file corrpted

### ISSUE THREAD

**Issue by bharathikannano** [apache/cordova-plugin-file-transfer#221]
hi 
while downloading file in ios 12 devices, after downloading opeing a pdf file it says file corrupted.
help me to close this issue

**Comment by santhoshbabu-d** [comment]
In Android also corrpted , tested with PDF, PNG

**Comment by timbru31** [comment]
Without any further details we unfortunately can't help.

Due to the age of this issue, I'm closing this one. If you still use this plugin and are affected by this bug, please create a new issue and use the provided issue template. Thanks!
