### ISSUE TITLE
Will there be any more releases after 1.7.1?

### ISSUE THREAD

**Issue by PabbleDabble** [apache/cordova-plugin-file-transfer#228]
1.7.1 was released Jan 2018 and there's been new code merged to master since then.  I know the plugin is deprecated, but I wasn't sure if that meant there would no longer be releases.  

I'd like to get the new changes from master using the standard installation method.  I'm aware that I can manually pull master.  

Will there be any more releases after 1.7.1?

**Comment by janpio** [comment]
Probably not, unless someone of the Apache Cordova committers is _really_ bored.

You can install the plugin from master instead from npm.
You can also fork the plugin and release an updated version with the changes from master as well.

**Comment by PabbleDabble** [comment]
Thank you for the quick response!   I will consider this issue closed.
