### ISSUE TITLE
iOS Library/NoCloud not being restored

### ISSUE THREAD

**Issue by hohae** [apache/cordova-plugin-file-transfer#230]
My app is using Library/NoCloud on iOS to store all its data. It builds up a directory structure. When doing a backup and restoring it to a new phone, alle the directories and files are gone. It doesn't matter if I do a "iCloud" backup or a "Backup to this computer" with iTunes. 

Is Library/NoCloud not part of any backup? Apple's documentation says that the complete app data is part of the backup.

**Comment by sithwarrior** [comment]
I know this  is an old question, but just to clarify, in a Cordova Application the Library/NoCloud folder, is explicitly marked to not be backed up.

You can read more about the file structure here [https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/](url)

**Comment by breautek** [comment]
Related: https://github.com/apache/cordova-plugin-file/issues/308

**Comment by breautek** [comment]
> I know this is an old question, but just to clarify, in a Cordova Application the Library/NoCloud folder, is explicitly marked to not be backed up.
> 
> You can read more about the file structure here https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/
