### ISSUE TITLE
Windows 10 - unable to resolve path to module

### ISSUE THREAD

**Issue by richpixel** [apache/cordova-plugin-file-transfer#232]
I realize the plugin is deprecated, and I do plan to migrate to the new standard, however I wanted to ask about this in case there's an easy answer.

On Windows 10, I'm getting a few 'Unable to resolve path to module' errors inside FileTransferProxy.js.

![Screenshot (7)](https://user-images.githubusercontent.com/1254778/56817969-aba71800-6814-11e9-9764-db4b8000dd1f.png)

Thanks for any guidance.

**Comment by timbru31** [comment]
Is this issue still relevant? If yes, please open a new issue and follow the template. This looks like a mis-configured IDE that does not know how the resolve the module. It is generally not recommended to alter the plugin's www code itself.
