### ISSUE TITLE
Error 413: FileTransferError request entity too large

### ISSUE THREAD

**Issue by kirstenfrager** [apache/cordova-plugin-file-transfer#233]
Specifically on iOS, I am getting a 413 error saying that the request entity is too large when I try and send a picture from my phone taken via camera. Depending on the image (obviously the size) it shows me this error, works at other times.

Has anyone experienced this and the best way to approach it? 

Is there any way to compress the image file before uploading it with fileTransfer?

Any help or guidance would be appreciated.
Thanks

**Comment by aurghyadip** [comment]
I am having the same problem when capturing a photo via camera. I'm even working with a photo of size 180x320 pixels.
Also, I'm converting it to Base64 and sending as a string. Receiving this error when sending the Base64 string.

**Comment by kirstenfrager** [comment]
@aurghyadip we managed to fix this issue as the error was coming from our own server. we had put a size limit on that side which was throwing this issue. taking that limitation off, it fixed the error as well.

**Comment by kirstenfrager** [comment]
@aurghyadip we managed to fix this issue as the error was coming from our own server. we had put a size limit on that side which was throwing this issue. taking that limitation off, it fixed the error as well. 

will close this issue I had, as was not related to plugin
