### ISSUE TITLE
Erorr code 3 when download multiple files

### ISSUE THREAD

**Issue by jsdev2018** [apache/cordova-plugin-file-transfer#235]
# Bug Report
When downloading with multiple instances of FileTransfer. Get Error code 3. Are multiple download not supported? 

## Problem
When downloading with multiple instances of FileTransfer. Get Error code 3. Are multiple download not supported? 

### What is expected to happen?
Multiple download of file happening at the same time. 

### What does actually happen?
The first file download fine. Second file get error code 3 in the return status. 

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by digaus** [comment]
@jsdev2018 Create one instance and call download multiple times. Works for me.

**Comment by WIlson-shuoshuoya** [comment]
@jsdev2018  What is the final solution? I also encountered this mistake when uploading multiple files.
