### ISSUE TITLE
 upload error code 3 "Software caused connection abort"

### ISSUE THREAD

**Issue by WIlson-shuoshuoya** [apache/cordova-plugin-file-transfer#241]
I did a circular upload of photos to request the server, but in the middle of the circle there were the following mistakes "Software caused connection abort", which left me at a loss.
Here is a code I uploaded.
`  let tempOptions: FileUploadOptions = {
                fileKey: 'file',
                fileName: photoDto.PhotoName,
                params: { type: photoType.ThumbPhoto, paramInfo: JSON.stringify(uploadPhotoDto) },
                chunkedMode: false
              }
              tempOptions.headers = {
                Connection: "close"
              }
              this.fileTransfer.upload(this.file.externalDataDirectory + photoDto.PhotoTempPath + photoDto.PhotoName, url, tempOptions, true).then(res => {
})
`

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
