### ISSUE TITLE
Ios13 downloads always fail

### ISSUE THREAD

**Issue by cqw12138** [apache/cordova-plugin-file-transfer#249]
# Bug Report

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
