### ISSUE TITLE
Media scanner after download file

### ISSUE THREAD

**Issue by aligassan** [apache/cordova-plugin-file-transfer#252]
# Feature Request

## Motivation Behind Feature

Media Scanner scans the entire phone for any media files like songs, photos and videos. Once the process finishes, photos, songs and videos show up on the gallery so you can easily see them.

## Feature Description

After i have finished downloading media or capturing the image and video file on my app . The media doesn't shows in gallery as image or video . So i have to restart my app then media will shows in gallery . So i have feature request to add media scanner After capturing or downloading media without restarting phone .

**Comment by jcesarmobile** [comment]
there are plugins for that, if you need that feature better use a separate plugin, but file-transfer can download any kind of files, most of them won't appear on the gallery anyway, so running the scanner after every download is not desired
