### ISSUE TITLE
Android uploading image got error with code is 5

### ISSUE THREAD

**Issue by AlwaysLoveme** [apache/cordova-plugin-file-transfer#253]
- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
i uploaded an pic with android ,but i got an error width " { code: 5, message: ENCODING_ERR}", some pictures would got this error , but some not, why?

### Version information
Cordova: Cordova 9.0,
plugin:  cordova-plugin-file-transfer@1.7.1
Other Frameworks: Ionic Framework 4

**Comment by timbru31** [comment]
Without any further details we unfortunately can't help.

If you still use this plugin and are affected by this bug, please create a new issue and use the provided issue template. Thanks!
