### ISSUE TITLE
Dowload and open pdf file in device 

### ISSUE THREAD

**Issue by hathemi** [apache/cordova-plugin-file-transfer#254]
i get pdf file from web service and i want to download it and open it in my android device.
using this code

> fileTransfer.download(url,this.file.externalDataDirectory+ filename).then((entry) => {
> this.localNotifications.schedule({
> text: ‘Téléchargement de fichier’+filename+’ est terminé !!’,
> led: ‘FF0000’,
> sound: null
> });

download the pdf file but connot open it because it has been saved as “error :invalid format” !!!with size 0.
any solution or suggestion please!

**Comment by timbru31** [comment]
Without any further details we unfortunately can't help.

If you still use this plugin and are affected by this bug, please create a new issue and use the provided issue template. Thanks!
