### ISSUE TITLE
File Upload Order Issue

### ISSUE THREAD

**Issue by sharawan** [apache/cordova-plugin-file-transfer#256]
Is it a way to upload images in a certain order. Currently the files being uploaded are in random order. I want to upload them in first in first out order

Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by ishigo1987** [comment]
You need to write your own logic to achieve what you desire

**Comment by breautek** [comment]
Files are uploaded in the order that you call `FileTransfer.upload` API. Note that the API is asynchronous so if you call this API multiple times, without waiting for the previous upload request, then the order of completion will be nondeterministic.
