### ISSUE TITLE
OnProgress event waits for full file download before reflecting the percentage of file downloaded

### ISSUE THREAD

**Issue by akashdeepsharma1991** [apache/cordova-plugin-file-transfer#257]
# Bug Report
The onprogress method is showing the percentage properly in console.log. But when i am binding it to html It waits till whole file is download and the increase the progress too 100
### What is expected to happen?
Should update the html view as the file download progressive

### Command or Code

```
 const url = 'http://mirrors.standaloneinstaller.com/video-sample/jellyfish-25-mbps-hd-hevc.3gp';
    this.fileTransfer.download(url, this.file.dataDirectory + 'jellyfish-25-mbps-hd-hevc.3gp').then((entry) => {
      console.log('download complete: ' + entry.toURL());
    }, (error) => {
      // handle error
    });
    let _this = this;
    this.fileTransfer.onProgress((progressEvent) => {
      // console.log(progressEvent,'progressEvent');
      let perc = Math.floor(progressEvent.loaded / progressEvent.total * 100);
      // perc = perc/100;
      console.log('perc',perc);
      item.progressValue = perc;
      console.log(item.progressValue);
      
    });
```

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
This plugin has no opinion on the UI. It simply just fires progress events, which as you say works.

In the example, the 3gp file is an extremely small file (300 bytes) so chances are the progress event it simply firing several times and finishes downloading before the next render.
