### ISSUE TITLE
Will it be updated this plugin for cordova-ios 6.0.0?

### ISSUE THREAD

**Issue by djdannycastillo** [apache/cordova-plugin-file-transfer#259]
Hi, recently cordova-ios has been released removing UIWebView. I've updated my project that uses this plugin but I'm receiving next error

CompileC /Users/danny/Library/Developer/Xcode/DerivedData/Mi_Historia_de_Salud-eezsltzhmqvgqkgvleasihprqjnn/Build/Intermediates.noindex/Mi\ Historia\ de\ Salud.build/Debug-iphonesimulator/Mi\ Historia\ de\ Salud.build/Objects-normal/x86_64/CDVFileTransfer.o Mi\ Historia\ de\ Salud/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Do you still support this plugin?

**Comment by breautek** [comment]
Technically this plugin is [deprecated](https://github.com/apache/cordova-plugin-file-transfer#deprecated),

but there was some discussion about bringing it back.

One person has mentioned:

> While I agree that we should somehow archive old code, I'm still -1 on a
deprecation of this plugin. (We've had some discussion about it here, too:
https://github.com/apache/cordova/issues/185)
XHR is not reliable and causes OOM errors when handling large data.

Feel free to add your input to the dev mailling discussion, especially if XHR is not a suitable replacement for you.

https://lists.apache.org/thread.html/rb04a84a08c88b4225fcc5f9d1b1e514c115872da0cb5fce739b0f108%40%3Cdev.cordova.apache.org%3E
