### ISSUE TITLE
Is it possible to transfer file in base64 format?

### ISSUE THREAD

**Issue by mikr96** [apache/cordova-plugin-file-transfer#277]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ /] Support Question

## Information

Error filetransfer => "http_status":422,"body":"{\"file\":[\"The file must be a string.\"]}"
### Environment, Platform, Device

Android

### Version information

Ionic 4

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Please use the issue template - I'm not sure if this is a bug or question. If it's a question you can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io) instead.

**Comment by CodeWithOz** [comment]
@mikr96 did you find a way to achieve this?
