### ISSUE TITLE
Cordova 10 Compatible?

### ISSUE THREAD

**Issue by dodomui** [apache/cordova-plugin-file-transfer#283]
# Bug Report
Unable to use to this plugin at cordova 10, cordova-ios 6.1.1

## Problem
I need to download image file from remote host to local device storage, if this is deprecated, any other method to achieve download function for Ionic V1? Thanks.

### Version information

```
Ionic:

   Ionic CLI         : 6.11.8 (/Users/nelsonmui/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.22

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.1.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.1 (/Users/nelsonmui/.nvm/versions/node/v12.16.1/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 12.0 Build version 12A7209
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Please see: https://github.com/apache/cordova-plugin-file-transfer/issues/266#issuecomment-686477119.
There is however no ETA for a new release on npm. Feedback from testing the master from git is very welcome
