### ISSUE TITLE
File upload breaking with Error code - 3 When updated from v1.7.2-dev to 2.0.0-dev

### ISSUE THREAD

**Issue by Anuj-Raghuvanshi** [apache/cordova-plugin-file-transfer#285]
# Bug Report

## Problem

Getting authorization error from my server while uploading file. Yet it works fine in previous version with `cordova-plugin-file@4.0.0`

### What is expected to happen?

It should also work fine even after updating plugin.

### What does actually happen?
It breaks with following error, yet I checked I am sending all these things and also reaching to plugin code(Checked from XCode) - 
![image](https://user-images.githubusercontent.com/22930446/93874257-b78c5780-fcf0-11ea-9e4c-511b9fba0c9c.png)

## Information
cordova-plugin-file : v6.0.2
cordova-plugin-file-transfer : v2.0.0-dev

### Environment, Platform, Device
Using ionic with cordova.
Platform - iOS.

### Version information
Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.0.0
   ios-deploy          : 1.11.1
   ios-sim               : 8.0.2
   NodeJS              : v12.18.4
   npm                    : 6.14.6
   OS                      : macOS Catalina
   Xcode                : Xcode 12.0 Build version 12A7209

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by christiaan** [comment]
This appears to be related to https://github.com/apache/cordova-plugin-file-transfer/pull/284
Can you try that branch?

**Comment by Anuj-Raghuvanshi** [comment]
Ohh Yeah @christiaan - That worked for me. Thanks for your response.

**Comment by HarelM** [comment]
I can also confirm that the headers are not being sent when using the user-agent override committed here: https://github.com/apache/cordova-plugin-file-transfer/commit/64bfd154b3ed8426ede8b66a2b7902cdf6122a21
@timbru31 can you have a look at the pull request which looks like basically reverts yours?
