### ISSUE TITLE
File transfer upload api issue with https url (ssl handshake exception)

### ISSUE THREAD

**Issue by Pratz007-tech** [apache/cordova-plugin-file-transfer#286]
I am genuinely in need of solution as soon as possible as we are waiting eagerly to go live soon . My issue is , with my url as https when I try to upload image with filetransfer it shows me following error : javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)at .... and so on. I have no clue where are changes needed and what are the changes.I am in contact with backend team based on the suggestion given by slack community (i.e webserver is sending an incorrect SSL cert chain) but we could not proceed. Any changes or implementations from client side (pure cordova app). Please suggest.Thanks & Kind Regards,Pratiksha

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
