### ISSUE TITLE
Can I still use this plugin for the latest Cordova?

### ISSUE THREAD

**Issue by DesignerApparelSales** [apache/cordova-plugin-file-transfer#288]
I heard this plugin got deprecated, But my app use 

var fileTransfer = new FileTransfer();
var uri = encodeURI("http://some.server.com/download.php");

fileTransfer.download()

 with no CORS problem.  Can it still be use with cordova 10.0?

**Comment by timbru31** [comment]
Yes, the current master works fine and we are preparing a new official release. No ETA though.

**Comment by DesignerApparelSales** [comment]
> Yes, the current master works fine and we are preparing a new official release. No ETA though.

Cool! Can you also fix the CORS issue that use WKWebView in the new plugin, If that even possible.
