### ISSUE TITLE
cordova-ios 6.1.1---xcodebuild: Command failed with exit code 65

### ISSUE THREAD

**Issue by GenZhangQ** [apache/cordova-plugin-file-transfer#289]
# Bug Report
xcodebuild: Command failed with exit code 65
## Problem
When I add plugin, the compilation fails, and I remove plugin, the compilation success
### What is expected to happen?
build success

### What does actually happen?
build error

## Information

The following build commands failed:
        CompileC /Users/mac/Library/Developer/Xcode/DerivedData/HelloCordova-gmphtdduevgtaofxubtazywmjoqo/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/x86_64/CDVFileTransfer.o /Users/mac/Desktop/workspace/test/platforms/ios/HelloCordova/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

### Command or Code

cordova build ios --debug --device

### Environment, Platform, Device

Environment: cordova-ios 6.1.1
Platform: vscode

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by GenZhangQ** [comment]
use XMLHttpRequest

**Comment by siphiwe** [comment]
I have this exact problem. Please share how you solved it. @GenZhangQ

**Comment by felixphase** [comment]
Same problem.
Please let me know how it is resolved @siphiwe @GenZhangQ

**Comment by coloz** [comment]
Same problem.

**Comment by klochko7** [comment]
Good day! I have the same problem. Help please. What can I do?

Use  ios: 6.1.1
cordova-plugin-file-transfer: 2.0.0-dev

Build failed.

The following build commands failed:
	CompileC /var/root/Library/Developer/Xcode/DerivedData/MyApp-dmqwhbrrkdtjbwagcrsqusbgfgsz/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/
	Objects-normal/x86_64/CDVFileTransfer.o /Users/ionicdev/Public/Ionic\ 
	5/Ionic/platforms/ios/MyApp/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

**Comment by timbru31** [comment]
Please share the full logs, the error is somewhere above in your output.

**Comment by zimejin** [comment]
I'm having the same issue as well. Any solutions so far?

**Comment by gklasen** [comment]
https://github.com/apache/cordova-plugin-file-transfer/issues/258#issuecomment-639355127
