### ISSUE TITLE
When to support android 10 or 11?

### ISSUE THREAD

**Issue by qqakashi** [apache/cordova-plugin-file-transfer#291]
# Feature Request

## Feature Description

Currently, the identification path cannot be found on the Android 10 device, indicating error code 1 and permission error

**Comment by sbellver** [comment]
Any update? After upgrade to API 29 (mandatory in November 2020 at Google Developer) file transfer don't works in android (still working in iOS)

**Comment by qqakashi** [comment]
@sbellver yes ，after upgrade to cordova-android 9.0 file transfer don't works in android

**Comment by KleggerKoder** [comment]
I'm having no trouble using this plugin on AndroidX with cordova-android 9.0 we're using the cordova-plugin-androidx-adapter plugin perhaps that is what you are missing @sbellver @qqakashi

**Comment by sbellver** [comment]
Yes, is an issue about AndroidManifest permissions about filestorage

I set it manually and works, but i think using androidx-adapter will be more permanent

Sergio Bellver Aliaga
Responsable de Proyectos
sbellver@tecneca.com
Skype: sbellver
M. 655 90 31 83

TECNECA Networks, S.L.
Innsomnia, Moll de Ponent Base 2, 46024, Valencia
info@tecneca.com
T. 96 326 81 48

www.tecneca.com

CONFIDENCIALIDAD: El contenido de esta comunicación, así como el de toda la documentación anexa, es confidencial y va dirigido únicamente al destinatario del mismo. En el supuesto de que usted no fuera el destinatario, le rogamos que, sin comunicar su contenido a terceros, nos lo haga y proceda a su destrucción.

PRIVACIDAD: Sus datos formarán parte de los ficheros y tratamiento de TECNECA NETWORKS, S.L. para poder mantener el contacto con usted, prestarle el servicio que nos ha solicitado y remitirle información sobre nuestra entidad a través de medios electrónicos. Su consentimiento y la prestación del servicio legitima el tratamiento de sus datos, que serán conservados mientras esté vigente nuestra relación y sean necesarios para las finalidades indicadas y cumplir nuestra obligaciones contractuales y legales (por ejemplo, en materia fiscal). Una vez cumplidas las obligaciones legales oportunas, serán suprimidos por completo.

**Comment by manelds** [comment]
I have the same problem. In the documentation of new Android versión (https://developer.android.com/about/versions/11/privacy/storage) talk about of permission "ACTION_MANAGE_STORAGE". 

I've add this permission to AndroidManifest.xml and it works fine:

`<uses-permission android:name="android.permission.ACTION_MANAGE_STORAGE" />`

**Comment by Topiya** [comment]
I am facing a same problem. Did anyone find any solution to this?

**Comment by sbellver** [comment]
Add https://www.npmjs.com/package/cordova-plugin-androidx-adapter plugin to your ionic app

**Comment by yogeshshsf** [comment]
I am facing same problem. i am in ionic 1 project using cordova 5.4.1. can you give solution for this?
@sbellver i tried to install androidx-adapter plugin but it is not getting in my project.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/48043733/107071201-5fbb3c80-680a-11eb-870b-be6c6192b931.png)

**Comment by sbellver** [comment]
You can (must) upgrade to cordova 8.
I'm on Cordova 9.0 and still with ionic 1

**Comment by jfoclpf** [comment]
> I've add this permission to AndroidManifest.xml and it works fine:
> 
> `<uses-permission android:name="android.permission.ACTION_MANAGE_STORAGE" />`

Anyone else tried this solution? Does it work for android 11?

**Comment by sebafra** [comment]
> > I've add this permission to AndroidManifest.xml and it works fine:
> > `<uses-permission android:name="android.permission.ACTION_MANAGE_STORAGE" />`
> 
> Anyone else tried this solution? Does it work for android 11?

Did you find a solution?

**Comment by jfoclpf** [comment]
@sebafra apparently that solution works only for Android 10. For Android 11 a working solution is to use a social sharing [plugin](https://www.npmjs.com/package/cordova-plugin-x-socialsharing) that allows the user to save the file whenever he wants, but it works only for saving a file outside of App's sandbox, not for reading.

**Comment by sebafra** [comment]
> @sebafra apparently that solution works only for Android 10. For Android 11 a working solution is to use a social sharing [plugin](https://www.npmjs.com/package/cordova-plugin-x-socialsharing) that allows the user to save the file whenever he wants, but it works only for saving a file outside of App's sandbox, not for reading. Check also this thread: [apache/cordova-plugin-file#426](https://github.com/apache/cordova-plugin-file/issues/426)

I need to read files from gallery, social sharing plugin allow to do this?

**Comment by jfoclpf** [comment]
> I need to read files from gallery, social sharing plugin allow to do this?

No, it is just a workaround to save files, not to read!

**Comment by richrichDev** [comment]
for anyone struggling with this , use this solution : 
modify FileTransfer.java as follow :

- means remove line of code
+ means add line of code
`
- import org.apache.cordova.Whitelist;
+import org.apache.cordova.AllowList;

-      Boolean shouldAllowRequest = null;
-        if (isLocalTransfer) {
-          shouldAllowRequest = true;
-      }
-      if (shouldAllowRequest == null) {
-          try {
-              Method gwl = webView.getClass().getMethod("getWhitelist");
-              AllowList whitelist = (AllowList)gwl.invoke(webView);
-              shouldAllowRequest = whitelist.isUrlAllowListed(source);
-          } catch (NoSuchMethodException e) {
-          } catch (IllegalAccessException e) {
-          } catch (InvocationTargetException e) {
-          }
-       }

+      Boolean shouldAllowRequest = null;
+         if (isLocalTransfer) {
+            shouldAllowRequest = true;
+        }
+        if (shouldAllowRequest == null) {
+            try {
+                Method gwl = webView.getClass().getMethod("getWhitelist");
+                AllowList whitelist = (AllowList)gwl.invoke(webView);
+                shouldAllowRequest = whitelist.isUrlAllowListed(source);
+            } catch (NoSuchMethodException e) {
+            } catch (IllegalAccessException e) {
+            } catch (InvocationTargetException e) {
+            }
+        }

`
