### ISSUE TITLE
Should update cordovaDependencies given new plugin version?

### ISSUE THREAD

**Issue by ath0mas** [apache/cordova-plugin-file-transfer#298]
https://github.com/apache/cordova-plugin-file-transfer/blob/88e39df8a547ba321ed02ec5dde4df68544bf09d/package.json#L34-L38

After recent bump to 2.0.0-dev, it seems when 2.0.0 will be released the `cordovaDependencies` block refering to `2.0.0` will apply and force `cordova` to out of _normal_ version. 🤔 

&rArr; Should this `cordovaDependencies` block be updated?

**Comment by breautek** [comment]
Yes.

Because this plugin is in the process of being revived from previously a deprecated state... I would personally be in favour of declaring that this plugin only works on cordova >= 10 (current cordova cli release). So the `cordovaDependencies` block should look something like:

```json
{ 
    "2.0.0": { 
         "cordova": ">=10" 
    },
    "3.0.0": {
         "cordova": ">100" 
    }
} 
```

**Comment by ath0mas** [comment]
@breautek thanks for your answer

Feel free to confirm this suggested change in the days or months to come and I'll add corresponding commit to PR #299
```
    "2.0.0": { 
         "cordova": ">=10" 
    },
```
