### ISSUE TITLE
execute onprogress the whole app was stuck on cordova6.3.1

### ISSUE THREAD

**Issue by cxpyear** [apache/cordova-plugin-file-transfer#302]
# Bug Report

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by cxpyear** [comment]
execute onprogress the whole app was stuck on cordova6.3.1

**Comment by breautek** [comment]
Closing this as the issue contains no information and cordova 6.3.1 is not a supported version.
