### ISSUE TITLE
Self-signed certificate  

### ISSUE THREAD

**Issue by walerio** [apache/cordova-plugin-file-transfer#303]
Download function return java.security.cert.CertPathValidatorException with self-signed certificate.
trustAllHosts is set to true

code example
fileTransfer.download('url', 'localpath', okCallback, koCallback, true)

**Comment by deryfebriantara** [comment]
> Download function return java.security.cert.CertPathValidatorException with self-signed certificate.
> trustAllHosts is set to true
> 
> code example
> fileTransfer.download('url', 'localpath', okCallback, koCallback, true)

I got the same issue with upload, on android device. have you solve the problem?

**Comment by breautek** [comment]
The ability to accept self-signed certs was intentionally removed on Android because having it in the code base will cause App store rejections in the code base.

See https://github.com/apache/cordova-plugin-file-transfer/pull/187 for more context.
