### ISSUE TITLE
How to install latest master version branch

### ISSUE THREAD

**Issue by vtellez** [apache/cordova-plugin-file-transfer#308]
Hello,

I would like to ask, how should I go about using the master version of the plugin?

If I install the plugin using this command:   cordova plugin add cordova-plugin-file-transfer

I always get version 1.7.1, which currently does not allow compiling on android 10, but I have seen that it was fixed a few days ago.

Could you tell me how to install this latest version from cordova?

Thanks in advance

**Comment by breautek** [comment]
It's not really recommended for production use as these changes haven't been voted on for release, but you can install using a git clone url. NPM will clone the repository as a NPM module.

e.g: `cordova plugin add https://github.com/apache/cordova-plugin-file-transfer.git`

If you have the plugin already installed, you'll need to first remove it by doing `cordova plugin remove cordova-plugin-file-transfer`.

Lastly, if you ARE going to use it in a production setting... then I'd recommend at least pinning the version to a specific commit. The latest [commit](https://github.com/apache/cordova-plugin-file-transfer/commit/2cdb0403a81821e144998c8d9a00d338d6ece3ee) at the of writing is `2cdb0403a81821e144998c8d9a00d338d6ece3ee` so you can use git # for commit/branch/tag identifier to install at that specific commit.

e.g.: `cordova plugin add https://github.com/apache/cordova-plugin-file-transfer.git#2cdb0403a81821e144998c8d9a00d338d6ece3ee`

Cheers!

**Comment by vtellez** [comment]
Thank you very much for the quick response.

I take note of the suggestion, to update the commit that corrects the problem. You have really helped me a lot.

Thanks for everything. Take care of yourself
