### ISSUE TITLE
cordova-plugin-file-transfer for Cordova Android 10

### ISSUE THREAD

**Issue by BrokerBisiako87** [apache/cordova-plugin-file-transfer#316]
### Issue Type

- [ ] Bug Report

## Description
HI friend! There is a problem when I compile the package. This message appears

**Task :app:compileDebugJavaWithJavac FAILED**
```
java\org\apache\cordova\filetransfer\FileTransfer.java:48: error: cannot find symbol
import org.apache.cordova.Whitelist;
                         ^
  symbol:   class Whitelist
  location: package org.apache.cordova
..\android\app\src\main\java\org\apache\cordova\filetransfer\FileTransfer.java:691: error: cannot find symbol
                Whitelist whitelist = (Whitelist)gwl.invoke(webView);
                ^
  symbol:   class Whitelist
  location: class org.apache.cordova.filetransfer.FileTransfer
..\android\app\src\main\java\org\apache\cordova\filetransfer\FileTransfer.java:691: error: cannot find symbol
                Whitelist whitelist = (Whitelist)gwl.invoke(webView);
                                       ^
  symbol:   class Whitelist
  location: class org.apache.cordova.filetransfer.FileTransfer
..\android\app\src\main\java\org\apache\cordova\filetransfer\FileTransfer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

## Information

If I remove the plugin, it compiles perfectly

 >  strippedNativeLibsDir   
 is deprecated and no longer used. Please remove it from your build configuration.

### Command or Code
cordova build android

### Version information

Cordova: Cordova CLI, Cordova Plugins

**Comment by CodeWithOz** [comment]
Disclaimer: I'm not a maintainer of this plugin. This issue has been fixed but hasn't been released yet. You can try installing from the latest commit in the master branch to see if the problem goes away.

**Comment by mahomedalid** [comment]
Just for the record you can try:

```
$ cordova plugin rm cordova-plugin-file-transfer
$ cordova plugin add https://github.com/apache/cordova-plugin-file-transfer
```

to use the git version. It works.

**Comment by brunoalex** [comment]
the file transfere to server not working on sdk 30 ..cant transfer to server

**Comment by CoooWeee** [comment]
Whitelisl is renamed to AllowList.

Renaming following in my project fixed the issue:

Whitelist => AllowList
addWhiteListEntry => addAllowListEntry
isUrlWhiteListed => isUrlAllowListed

**Comment by amisanjid** [comment]
> $ cordova plugin add https://github.com/apache/cordova-plugin-file-transfer

Is "cordova plugin add https://github.com/apache/cordova-plugin-file-transfer" is enough for making AJAX request without CORS??
