### ISSUE TITLE
No Release for 3 Years - Code Being Distributed is Not Up to Date

### ISSUE THREAD

**Issue by allidoisace** [apache/cordova-plugin-file-transfer#320]
# Bug Report

### What is expected to happen?
Latest Release should be up to date with something closer than 2017.

### What does actually happen?
Errors still exist that have been closed for over a year.

## Information

Pretty Self Explanatory

### Command or Code

`npm install cordova-plugin-file-transfer@latest`

### Environment, Platform, Device

Mac using Capacitor

### Version information

XCode 13
Capacitor 3

## Checklist

- [-] I searched for existing GitHub issues
- [-] I updated all Cordova tooling to most recent version
- [-] I included all the necessary information above

**Comment by muuvmuuv** [comment]
Yes can we please have a new release? It seems the package.json in on some v2 but npm is still on v1.x

**Comment by Yura13** [comment]
Hi @erisu 
Do you know when the new version of the plugin will be released?

**Comment by fredroo** [comment]
@erisu Do you know when the new version of the plugin will be released?

wait a version to capacitor compatible

**Comment by jcesarmobile** [comment]
The plugin was deprecated, so that’s why there weren’t any released for a long time.
Now it has been undeprecated and work is being done before a release can be made, so be patient.
