### ISSUE TITLE
With iOS, I think -file-transfer needs to be updated to work with -plugin-file v7

### ISSUE THREAD

**Issue by phusting** [apache/cordova-plugin-file-transfer#347]
When I go to compile platform iOS 6.2 with -plugin-file v7 and -file-transfter 1.7.1 it says that "CDVFile.h" file not found.  CDVFileTransfer.h

Another person mention that file-transfer 1.7.1 needs to be updated to support the new -file plugin

### Version information
iOS 6.2
CLI 11

**Comment by pixellet14** [comment]
I think I now will have to go to god finally to have a solution for this problem.

**Comment by rolinger** [comment]
For anyone still needing a solution, see this post:

https://github.com/apache/cordova-plugin-file-transfer/issues/339#issuecomment-1450747708

**Comment by jcesarmobile** [comment]
It’s now updated to work with file plugin 8.0.0
