### ISSUE TITLE
Kindly advise if there is an alternative to FileTransfer / FileUpload for use with Capacitor 4. Thanks

### ISSUE THREAD

**Issue by mahen23** [apache/cordova-plugin-file-transfer#354]
Kindly advise if there is an alternative to FileTransfer / FileUpload for use with Capacitor 4. Thanks

**Comment by SerjMalko** [comment]
@mahen23, Do you find anything?

**Comment by mahen23** [comment]
> @mahen23, Do you find anything?

still nothing mate.

**Comment by breautek** [comment]
https://capacitorjs.com/docs/apis/http is likely the closest alternative. It states it uses native HTTP libraries instead of the browser API.

Closing because this isn't really related to Cordova.
