### ISSUE TITLE
Undeprecate this plugin

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-plugin-file-transfer#363]
# Feature Request

There is currently no alternative to downloading large files as they are transferred in memory and crashes on some mobile devices.

This plugin works but it's latest version is not released and it has a deprecation warning.

It would be great if this plugin could be undeprecated and a new version will be released to npm.

## Feature Description

Release the current version.
I'll be happy to help given the right guidance.

## Alternatives or Workarounds

I'm currently using a version from a commit:
`"cordova-plugin-file-transfer": "github:apache/cordova-plugin-file-transfer#ec11d2fd0e87d7d9e0ba94b1989ffb71af1c3c96",`

cc: @erisu @timbru31

**Comment by jcesarmobile** [comment]
the plugin was undeprecated on https://github.com/apache/cordova-plugin-file-transfer/pull/267
but there has not been any releases yet

**Comment by HarelM** [comment]
Is it possible to carve a new release then @jcesarmobile?

**Comment by jcesarmobile** [comment]
No, it’s not ready for being released

**Comment by HarelM** [comment]
Is there anything I can do in order to help with the process of making it ready?
