### ISSUE TITLE
The plugin 2.0.0-dev will not load on Android 6.0 and below.

### ISSUE THREAD

**Issue by RonnySchleicher** [apache/cordova-plugin-file-transfer#366]
# Bug Report/Question
Hello, I have a simple question, but unfortunately I can't find an exact answer.
What is the minimum supported Android version?
The plugin 2.0.0-dev will not load on Android 6.0 and below.

## Logcat Message:
![image](https://github.com/apache/cordova-plugin-file-transfer/assets/1914203/7caef346-bff5-40d3-bb4b-4769c72384f2)

## Source Code in FileTransfer.js (let is the problem)
![image](https://github.com/apache/cordova-plugin-file-transfer/assets/1914203/9d4cc3e7-bcb1-4c0a-9021-ec958c8e5a1a)

### Version information
Cordova: 11
cordova-plugin-file-transfer: 2.0.0-dev
Android Studio Giraffe 2022.3.1 (AGP 8.1.0)
Windows 11 - lastest Version

**Comment by breautek** [comment]
> What is the minimum supported Android version?

Plugins generally follow the minimum supported version of the platform, which the android current release has a min SDK of 24.

The error is a JS error though and doesn't really have anything to do with android SDK levels, but rather the webview version you're running doesn't have support for the `let` keyword. `let` was introduced in Chrome 49.

Based on AOSP emulators, the webview version that ships with a factory AOSP on API 24 is Chrome 51 if I recall correctly. You can double check the `Android System Webview` version to confirm if you're running something less than 49.

While AOSP emulators have a really low webview version, in practice most people running on the same device will likely have a more modern webview version as they will auto update unlike AOSP emulators. This can also be tested by using a Google Play enabled emulator, signing into Google Play and install the updates. We do try to support the "factory" webview versions based on the AOSP emulators though.
